name: flutter_google_maps
version: 4.1.2
homepage: https://github.com/taskhunt/flutter_google_maps
description: A Flutter plugin for integrating Google Maps in iOS, Android and Web applications. It is a wrapper of google_maps_flutter for Mobile and google_maps for Web.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^3.1.0
  google_maps_flutter: ^2.2.4
  google_directions_api: ^0.9.1
  google_maps: ^6.2.0
  http: ^0.13.5
  flinq: ^2.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png